name: Basic Checking

on: push

jobs:
  formatting_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
          args: "--skip-sorting-imports --replace"
      - name: Build Attempt
        run: mvn -B clean package --file pom.xml